services:
  postgres:
    image: postgres:18
    container_name: postgres

    ports:
      - "${PORT}:5432"

    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASS}

    volumes:
      - ./data:/var/lib/postgresql/docker